---
- name: Utilize blocks, rescue, and alway
  hosts: databases
  become: true
  
  tasks:
    - name: Update databases
      block:
        - name: Display an update message
          debug:
            msg: "Updating Database"
       
        - name: install postgreSQL server to latest version
          apt:
            name: postgresql-server
            state: latest
      rescue:
        - name: Displays error message
          debug:
            msg: "Update filed, restarting database to correct issues"    

        - name: Restart the database if upgrade failed
          service:
            name: postgresql
            state: restarted

      always:
        - name: notify user of reboot after upgrade attempt
          debug:
            msg: "Update process has completed. Rebooting the server"

        - name: Reboot the system
          reboot:
