---
- name: create new users
  hosts: all
  become: true
  vars:
    web_users:
      - webuser01
      - webuser02
      - webuser03
  
  tasks:
    - name: create DB ysers
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ db_users }}"
      when: "'databases' in group_names"
    
    - name: create web users
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ web_users }}"
      when: "'webservers' in group_names"
