---
- name: create users and groups
  hosts: nodes
  
  tasks:
    - name: create groups
      group:
        name: "{{ item }}"
        state: absent
      loop:
          - paas
          - iaas

    - name: create users
#      debug:
#        msg: "{{ item.value }}"
      user:
        name: "{{ item.name }}"
        state: absent
        groups: "{{ item.groups }}"
      loop:
        - { name: 'Lohith', groups: 'iaas' }
        - { name: 'Vikas', groups: 'paas' }
        - { name: 'Ranjith', groups: 'iaas' }
        - { name: 'Vishal', groups: 'paas' }
