<<<<<<< HEAD
---
- name: New user will be created
  hosts: nodes
  become: true

  tasks:
    - name: Load variable from encrypted file
      include_vars:
        file: secret

    - name: Display the encrypted variable
      debug:
        msg: "{{ secret }}"
      no_log: true

    - name: user gets created
      user:
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['descript'] }}"
        password: "{{ username['test']['password'] }}"
        state: present

=======
#ansible -i inventory.yml all -m file -a "path=/tmp/a.txt state=touch"
---
- hosts: all
  tasks:
  - name: exeute ping command
    ping:
  - name: exeute setup command
    setup:
  - name: create a direcotry
    file:
      path: /tmp/abcdir
      state: directory
  - name: create a file
    file:
      path: /tmp/abcdir/a.txt
      state: touch
>>>>>>> b66e8ff8ebddb3daec1d726cc502452a438db047
