- name: Gather Facts and Use Them
  hosts: webservers
  gather_facts: yes  # Explicitly request fact gathering (default is yes)
  tasks:
    - name: Display OS Family
      ansible.builtin.debug:
        msg: "The target host's OS family is {{ ansible_os_family }}."

    - name: Display Available Memory
      ansible.builtin.debug:
        msg: "The target host has {{ ansible_memory_mb.real.total }} MB of available memory."
