---
- name: Deploy files using a Jinja2 template
  hosts: all
  become: true

  tasks:
    - name: Update host files
      template:
        src: hosts.j2
        dest: /etc/hosts
#        owner: root
#        group: root
#        mode: "0644"



