---
- name: setup apt repo
  apt_repository:
    repo: ppa:ondrej/apache2
- name: install apache2 package
  apt:
    name: "{{ packagename }}"
    state: latest
- name: copy index file to html dir
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: restart apache2 server
- name: copy ports file to /etc/apache2/ports.conf
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: restart apache2 server

# - name: apache2 port 81
#   lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 81" state=present
#   notify: service restarted

- name: start apache2 server
  service:
    name: "{{ packagename }}"
    state: started
    enabled: yes
- name: debug vars
  debug:
    msg: "version value:  {{ version }}"