## docker container run -name c1 -it --detach python
---
- name: install pre-requesities for docker
  hosts: localhost
  tags: prereqs
  tasks:
  - pip:
      name: requests

- name: install containers using ansible
  hosts: localhost
  module_defaults:
    community.docker.docker_container:
      force_kill: true
      state: absent

  tasks:
  - community.docker.docker_container:
      name: "c{{ item }}"
      image: python
      tty: true
      interactive: true
    loop: "{{ range(1,4) }}"
      #- c1
      #- c2
      #- c4
  - community.docker.docker_container:
      name: sleeper
      image: python:3.6
      command: sleep infinity